### ISSUE TITLE
Cannot get list video

### ISSUE THREAD

**Issue by tuhalang** [renyijiu/douyin_downloader#14]
I only got response: get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}

**Comment by khangpropk123** [comment]
i got the same error :(

**Comment by renyijiu** [comment]
@tuhalang @khangpropk123 I got this problem during the test. You can get data by retrying the same signature. The reason is not clear for the time being. If you have any suggestions, please tell me.

**Comment by khangpropk123** [comment]
@renyijiu Can you tell me more clearly?

**Comment by renyijiu** [comment]
@khangpropk123 If you are sure that the link can get videos, please retry to get data again. When I was developing, I found that using the same signature to repeatedly request the link, sometimes got data and sometimes no data, and the specific reason has not been identified for the time being.If you have ideas, please tell me to optimize, ths.

**Comment by tuhalang** [comment]
in the first time i run project i can get data in json file and i can download videos. But in the second time until now i can't. the response only is {'has_more': 0, 'status_code': 0, 'aweme_list': []}. nothing more.

**Comment by lvhuayu** [comment]
> I only got response: get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}

I also got the same response
