### ISSUE TITLE
ItemId: 0, uid: 0

### ISSUE THREAD

**Issue by huy99ls01** [renyijiu/douyin_downloader#16]
![Screenshot (4)](https://user-images.githubusercontent.com/33337649/79050482-89d8b800-7c54-11ea-81bb-36bba775873a.png)

why i got itemId = 0 and, uid =0, i get douyin link in vietnam

here the link: 

https://v.douyin.com/cTgexD/

**Comment by renyijiu** [comment]
@huy99ls01  click the link, i got the img , so i don't know the video right?

<img width="942" alt="图片" src="https://user-images.githubusercontent.com/8318266/79061809-474fc380-7cc6-11ea-9df2-b6c90a7e3ddf.png">

**Comment by huy99ls01** [comment]
> @huy99ls01 click the link, i got the img , so i don't know the video right?
> 
> <img alt="图片" width="942" src="https://user-images.githubusercontent.com/8318266/79061809-474fc380-7cc6-11ea-9df2-b6c90a7e3ddf.png">

yeah i figure it out, thank you and 1 more question.

i have successfull download video with your code but sometime it work and sometime it not work, can you guide me how to fix that problem? Thank you

**Comment by renyijiu** [comment]
> > @huy99ls01 click the link, i got the img , so i don't know the video right?
> > <img alt="图片" width="942" src="https://user-images.githubusercontent.com/8318266/79061809-474fc380-7cc6-11ea-9df2-b6c90a7e3ddf.png">
> 
> yeah i figure it out, thank you and 1 more question.
> 
> i have successfull download video with your code but sometime it work and sometime it not work, can you guide me how to fix that problem? Thank you

Guessing is a problem with signatures. Sometimes the same signature has data, sometimes it does n’t. And I haven't thought about how to deal with it, if you have ideas, please let me know

**Comment by huy99ls01** [comment]
> > > @huy99ls01 click the link, i got the img , so i don't know the video right?
> > > <img alt="图片" width="942" src="https://user-images.githubusercontent.com/8318266/79061809-474fc380-7cc6-11ea-9df2-b6c90a7e3ddf.png">
> > 
> > 
> > yeah i figure it out, thank you and 1 more question.
> > i have successfull download video with your code but sometime it work and sometime it not work, can you guide me how to fix that problem? Thank you
> 
> Guessing is a problem with signatures. Sometimes the same signature has data, sometimes it does n’t. And I haven't thought about how to deal with it, if you have ideas, please let me know

i guess it not about signature because i just download single video and i dont see any line of code using signature

**Comment by huy99ls01** [comment]
> > > > @huy99ls01 click the link, i got the img , so i don't know the video right?
> > > > <img alt="图片" width="942" src="https://user-images.githubusercontent.com/8318266/79061809-474fc380-7cc6-11ea-9df2-b6c90a7e3ddf.png">
> > > 
> > > 
> > > yeah i figure it out, thank you and 1 more question.
> > > i have successfull download video with your code but sometime it work and sometime it not work, can you guide me how to fix that problem? Thank you
> > 
> > 
> > Guessing is a problem with signatures. Sometimes the same signature has data, sometimes it does n’t. And I haven't thought about how to deal with it, if you have ideas, please let me know
> 
> i guess it not about signature because i just download single video and i dont see any line of code using signature

i have download some video of a user but i just a few video, is it about signature? thank you

**Comment by renyijiu** [comment]
> > > > > @huy99ls01 click the link, i got the img , so i don't know the video right?
> > > > > <img alt="图片" width="942" src="https://user-images.githubusercontent.com/8318266/79061809-474fc380-7cc6-11ea-9df2-b6c90a7e3ddf.png">
> > > > 
> > > > 
> > > > yeah i figure it out, thank you and 1 more question.
> > > > i have successfull download video with your code but sometime it work and sometime it not work, can you guide me how to fix that problem? Thank you
> > > 
> > > 
> > > Guessing is a problem with signatures. Sometimes the same signature has data, sometimes it does n’t. And I haven't thought about how to deal with it, if you have ideas, please let me know
> > 
> > 
> > i guess it not about signature because i just download single video and i dont see any line of code using signature
> 
> i have download some video of a user but i just a few video, is it about signature? thank you

It ’s hard to say, you need to check the web page to determine
