### ISSUE TITLE
无法获取视频，报错如下

### ISSUE THREAD

**Issue by sljx** [renyijiu/douyin_downloader#17]
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
get empty list, {'has_more': 0, 'status_code': 0, 'aweme_list': []}
retry...
Traceback (most recent call last):
  File "douyin.py", line 539, in <module>
    CrawlerScheduler(content, favorite)
  File "douyin.py", line 341, in __init__
    self.scheduling(favorite)
  File "douyin.py", line 350, in scheduling
    self.download_user_videos(user_id, favorite)
  File "douyin.py", line 368, in download_user_videos
    self.push_download_job(uid, dytk, 0, favorite)
  File "douyin.py", line 379, in push_download_job
    list_json = get_list_by_uid(user_id, dytk, cursor, favorite)
  File "douyin.py", line 116, in get_list_by_uid
    res_json = json.loads(r.html.text)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by renyijiu** [comment]
@sljx 能够提供下相关的视频链接吗？

**Comment by sljx** [comment]
https://v.douyin.com/JJQBHo2/

**Comment by renyijiu** [comment]
@sljx 可以重新拉取代码试试
