### ISSUE TITLE
取list不行

### ISSUE THREAD

**Issue by S1U** [renyijiu/douyin_downloader#18]
<img width="1382" alt="Screen Shot 2020-06-07 at 4 57 17 PM" src="https://user-images.githubusercontent.com/4564129/83964489-0c41c900-a8e0-11ea-85a9-8bdeb6e1983a.png">

**Comment by renyijiu** [comment]
可以按照错误提示自己搜索下，如果代码有问题，欢迎提交你的解决方案

**Comment by S1U** [comment]
不知道对这个空 list 从何入手，请教下是哪方面可能有问题？

**Comment by renyijiu** [comment]
最简单的你直接重试运行，出错的话你可以看输出日志的最后一行提示搜索一下，应该请求网页数据出现了问题

**Comment by eromoe** [comment]
same error here .

**Comment by eromoe** [comment]
Found solution for  `pyppeteer.errors.NetworkError: Protocol error Target.createTarget: Target closed.`

```
pip install websockets==6
```

@renyijiu  assign in requirements.txt would be good .

So, the left problem is endless empty list ...  I have no idea for now .

**Comment by renyijiu** [comment]
@eromoeIf you test and find that the code is working properly, welcome to submit your code

**Comment by eromoe** [comment]
![image](https://user-images.githubusercontent.com/3938751/85188821-13070d80-b2dc-11ea-8cc6-8f8dc6f6e8af.png)

Webpage is empty in chrome mobile mode , even empty in mobile browser . So there may be a special UA or  something called  signature you mention in other threads . 
That is really hard , unless somebody inside tiktok can leak detail to us .

**Comment by eromoe** [comment]
@renyijiu  Did you try this  ?
https://github.com/FioraLove/Net-Spider/tree/develop/%E6%8A%96%E9%9F%B3

**Comment by renyijiu** [comment]
@eromoe Sorry, i have not tried. you may use the project to replace the signature and try download the video, if it works perfectly， welcome to sumbit your code to optimize this project
