### ISSUE TITLE
可以下载用户收藏视频，但是会一直retry

### ISSUE THREAD

**Issue by hunya2017** [renyijiu/douyin_downloader#2]
get empty list, {'has_more': 1, 'status_code': 0, 'min_cursor': 0, 'aweme_list': []}
retry...

**Comment by renyijiu** [comment]
> get empty list, {'has_more': 1, 'status_code': 0, 'min_cursor': 0, 'aweme_list': []}
> retry...

是的，因为签名获取的数据有时是空的，所以加了判断重试！具体原因还未查到，如果有想法，欢迎交流
