### ISSUE TITLE
ssl problem

### ISSUE THREAD

**Issue by einsli** [renyijiu/douyin_downloader#20]
When I use the scripts python douyin.py --url=https://v.douyin.com/JRoydED/, I jsut encountered the problem following
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromium-browser-snapshots/Mac/575458/chrome-mac.zip (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))). I don't know how to solve it.

**Comment by renyijiu** [comment]
@einsli  Some dependencies need to be downloaded from google, please confirm that your network can access google
