### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by shone5499** [renyijiu/douyin_downloader#21]
Traceback (most recent call last):
  File "douyin.py", line 574, in <module>
    CrawlerScheduler(content, favorite)
  File "douyin.py", line 370, in __init__
    self.scheduling(favorite)
  File "douyin.py", line 379, in scheduling
    self.download_user_videos(user_id, favorite)
  File "douyin.py", line 396, in download_user_videos
    uid, dytk = get_user_info(user_id)
  File "douyin.py", line 78, in get_user_info
    uid = r.html.search('uid: "{uid}"')['uid']
TypeError: 'NoneType' object is not subscriptable

**Comment by renyijiu** [comment]
@shone5499 你可以debug一下，看下r.html输出了什么信息？

**Comment by imldy** [comment]
+1 ，我的也是这样，@renyijiu 我输出r.html为`<HTML url='https://www.iesdouyin.com/share/user/2159043692700000'>`。（最后几位已脱敏处理）

**Comment by chow459** [comment]
@renyijiu 好像server改变了检测爬虫机制？随便一个链接都不行了，得到的url对，但是url的得到的网页没有视频信息。更具体的我也不太明白了。

**Comment by renyijiu** [comment]
@mars747 我还没测试验证过，暂时不清楚，你可以自己排查看看，是否存在签名算法更新之类的问题

**Comment by RIP-GitHub** [comment]
@renyijiu 签名算法没做更新，正常访问也经常出不了数据，10次有1次就不错了，初步判断是后端接口故意设置的，感觉这个接口过不了多久就会被砍掉了

**Comment by renyijiu** [comment]
@RIP-GitHub 目前是依赖web版本，如果放弃了那也没有办法。更优的方案是逆向app，但这不是我擅长的东西
