### ISSUE TITLE
请问无水印视频是修改视频URL的哪个参数呢？

### ISSUE THREAD

**Issue by tangniyuqi** [renyijiu/douyin_downloader#3]
目前从HTML解析出来类似这样：https://aweme.snssdk.com/aweme/v1/playwm/?s_vid=93f1b41336a8b7a442dbf1c29c6bbc563cee1a2ae9eee323b4f0155dba57fdd61ae2c983b1893ec7074426e7c178662f668166c7cfb860c615ca576132238e0b&line=0

这个链接的怎么替换才是无水印的视频链接

**Comment by renyijiu** [comment]
@tangniyuqi 这个是播放链接，具体我没有研究过，但是可以通过获取video_id，然后构建请求获取下载链接

**Comment by renyijiu** [comment]
@tangniyuqi 已经添加单个视频下载功能，可以使用`python douyin.py -u http://v.douyin.com/AbHd2X/ -s`下载

**Comment by zszen** [comment]
@renyijiu 你好，看一下这个视频
`python3 douyin.py -s -u http://v.douyin.com/ULu528/`
这个视频有1分多，属于长视频，无法通过此参数获得完整视频

**Comment by renyijiu** [comment]
@zszen 你好，我测试下载没有发现问题，视频时长1分21秒；请确认下程序执行是否有问题

![image](https://user-images.githubusercontent.com/8318266/62853623-8a186080-bd1f-11e9-873c-fd31f6fcc965.png)

**Comment by zszen** [comment]
@renyijiu 可以了，我又试了一次 
![image](https://user-images.githubusercontent.com/1890538/62855075-c483fc80-bd23-11e9-8aa4-a5d59cd83de7.png)
