### ISSUE TITLE
无法 git clone

### ISSUE THREAD

**Issue by lbcake** [renyijiu/douyin_downloader#5]
![image](https://user-images.githubusercontent.com/26319880/62428893-a9205c80-b739-11e9-8eb8-7fe51fe7deb5.png)

**Comment by lbcake** [comment]
![image](https://user-images.githubusercontent.com/26319880/62429098-d9b5c580-b73c-11e9-9da1-244ec5328518.png)
win7  直接下的解压包 解压出来   python是3.6 执行 报上图错误       没有重做virtualenv   本身的py3.6

**Comment by renyijiu** [comment]
@lbcake git clone请查看你的github的ssh key已设置正确，这个不属于项目问题。

**Comment by renyijiu** [comment]
@lbcake 执行错误，请确认下你的依赖已经安装，页面最后一行已经告知，`ImportError: cannot import name 'Deque'`

**Comment by lbcake** [comment]
> @lbcake git clone请查看你的github的ssh key已设置正确，这个不属于项目问题。

ssh key  从哪里看啊？

**Comment by lbcake** [comment]
> @lbcake 执行错误，请确认下你的依赖已经安装，页面最后一行已经告知，`ImportError: cannot import name 'Deque'`
![image](https://user-images.githubusercontent.com/26319880/62438988-8bc0b200-b77c-11e9-94e2-d723be3c652c.png)
yil依赖关系 全都装了啊  我不知道哪里的错误啊！！
requirements.txt 装了    requests-html 也装了啊  我不知道还缺啥

**Comment by renyijiu** [comment]
> > @lbcake git clone请查看你的github的ssh key已设置正确，这个不属于项目问题。
> 
> ssh key 从哪里看啊？

https://help.github.com/cn/articles/connecting-to-github-with-ssh

**Comment by lbcake** [comment]
> > > @lbcake git clone请查看你的github的ssh key已设置正确，这个不属于项目问题。
> > 
> > 
> > ssh key 从哪里看啊？
> 
> https://help.github.com/cn/articles/connecting-to-github-with-ssh

没必要git了吧  我直接下的zip 解压出来的    本身py3.6 以来都装了    还是不行。  你那个git clone 是不是linux 环境配的 我是win7

**Comment by renyijiu** [comment]
@lbcake 请尝试使用virtualenv，单独安装依赖试试

**Comment by lbcake** [comment]
> @lbcake 请尝试使用virtualenv，单独安装依赖试试

能方便留个联系方式吗？ 我这边是真找不到解决问题了

**Comment by renyijiu** [comment]
@lbcake 你可以单独测试下 https://github.com/psf/requests-html  这个包，命令行测试下是否可以运行？联系方式我的主页应该有 me@renyijiu.com

**Comment by lbcake** [comment]
![image](https://user-images.githubusercontent.com/26319880/62476045-dcfe8f00-b7d8-11e9-89d7-dda41c444402.png)
太恶心了  为啥非要用requests-html

**Comment by lbcake** [comment]
> @lbcake 你可以单独测试下 https://github.com/psf/requests-html 这个包，命令行测试下是否可以运行？联系方式我的主页应该有 [me@renyijiu.com](mailto:me@renyijiu.com)

依赖包都装上了    requests-html测试都过不去啊  两个测试文件 都不行...O.O

**Comment by renyijiu** [comment]
> ![image](https://user-images.githubusercontent.com/26319880/62476045-dcfe8f00-b7d8-11e9-89d7-dda41c444402.png)
> 太恶心了 为啥非要用requests-html

这是我的技术选择，如不满意，你可以自己对代码进行修改，欢迎提交pr或者开源你的修改

**Comment by renyijiu** [comment]
> > @lbcake 你可以单独测试下 https://github.com/psf/requests-html 这个包，命令行测试下是否可以运行？联系方式我的主页应该有 [me@renyijiu.com](mailto:me@renyijiu.com)
> 
> 依赖包都装上了 requests-html测试都过不去啊 两个测试文件 都不行...O.O

项目地址已经提供，请自己多搜索查看，如果还有问题，可以去项目提对应的issue请求帮助！

**Comment by lbcake** [comment]
> > > @lbcake 你可以单独测试下 https://github.com/psf/requests-html 这个包，命令行测试下是否可以运行？联系方式我的主页应该有 [me@renyijiu.com](mailto:me@renyijiu.com)
> > 
> > 
> > 依赖包都装上了 requests-html测试都过不去啊 两个测试文件 都不行...O.O
> 
> 项目地址已经提供，请自己多搜索查看，如果还有问题，可以去项目提对应的issue请求帮助！

https://blog.csdn.net/m0_37561765/article/details/78714603

**Comment by lbcake** [comment]
> > > @lbcake 你可以单独测试下 https://github.com/psf/requests-html 这个包，命令行测试下是否可以运行？联系方式我的主页应该有 [me@renyijiu.com](mailto:me@renyijiu.com)
> > 
> > 
> > 依赖包都装上了 requests-html测试都过不去啊 两个测试文件 都不行...O.O
> 
> 项目地址已经提供，请自己多搜索查看，如果还有问题，可以去项目提对应的issue请求帮助！

https://segmentfault.com/a/1190000010600365
