### ISSUE TITLE
当一个视频有点击查看完整版的时候无法下载完整版视频

### ISSUE THREAD

**Issue by zszen** [renyijiu/douyin_downloader#6]
这个人的主页第一条视频就是这样
http://v.douyin.com/Pqgn6Q/
视频是这个
http://v.douyin.com/Pqbf7r/ 

原视频有几分钟，下载的只有18秒

**Comment by renyijiu** [comment]
@zszen 大概看了眼，网页版视频播放也只有18秒，不确定是否是网页版的限制，欢迎你研究下
